# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10d244f1cfe31d3c5631f79798f4baa3b30b00458809b626b64ef49f3fe0a16e67c09f79d295fb29ee9807198d0028b104a0c72e6cc6a209c6e8496eba879d88

test:
  secret_key_base: 44e061cce52e10e9c537b42942801df8d34bd789352c4370d7d089c7f5507d961863e017c861a459ed38dc6e1e40c6a562273d0d4d05e4404c2b1c78438a4d18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
